package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PeartArticulo generated by hbm2java
 */
public class PeartArticulo  implements java.io.Serializable {


     private Integer peartNumart;
     private String peartNomart;
     private String peartDescri;
     private BigDecimal peartPreart;
     private int peartCantid;
     private Set<Pedet> pedets = new HashSet<Pedet>(0);

    public PeartArticulo() {
    }

	
    public PeartArticulo(String peartNomart, String peartDescri, BigDecimal peartPreart, int peartCantid) {
        this.peartNomart = peartNomart;
        this.peartDescri = peartDescri;
        this.peartPreart = peartPreart;
        this.peartCantid = peartCantid;
    }
    public PeartArticulo(String peartNomart, String peartDescri, BigDecimal peartPreart, int peartCantid, Set<Pedet> pedets) {
       this.peartNomart = peartNomart;
       this.peartDescri = peartDescri;
       this.peartPreart = peartPreart;
       this.peartCantid = peartCantid;
       this.pedets = pedets;
    }
   
    public Integer getPeartNumart() {
        return this.peartNumart;
    }
    
    public void setPeartNumart(Integer peartNumart) {
        this.peartNumart = peartNumart;
    }
    public String getPeartNomart() {
        return this.peartNomart;
    }
    
    public void setPeartNomart(String peartNomart) {
        this.peartNomart = peartNomart;
    }
    public String getPeartDescri() {
        return this.peartDescri;
    }
    
    public void setPeartDescri(String peartDescri) {
        this.peartDescri = peartDescri;
    }
    public BigDecimal getPeartPreart() {
        return this.peartPreart;
    }
    
    public void setPeartPreart(BigDecimal peartPreart) {
        this.peartPreart = peartPreart;
    }
    public int getPeartCantid() {
        return this.peartCantid;
    }
    
    public void setPeartCantid(int peartCantid) {
        this.peartCantid = peartCantid;
    }
    public Set<Pedet> getPedets() {
        return this.pedets;
    }
    
    public void setPedets(Set<Pedet> pedets) {
        this.pedets = pedets;
    }




}


