package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PecliCliente generated by hbm2java
 */
public class PecliCliente  implements java.io.Serializable {


     private Integer pecliNumcli;
     private String pecliNomcli;
     private String pecliCitcli;
     private BigDecimal pecliDescli;
     private Integer pecliIndtyp;
     private Set<PevntVentas> pevntVentases = new HashSet<PevntVentas>(0);

    public PecliCliente() {
    }

	
    public PecliCliente(String pecliNomcli, String pecliCitcli) {
        this.pecliNomcli = pecliNomcli;
        this.pecliCitcli = pecliCitcli;
    }
    public PecliCliente(String pecliNomcli, String pecliCitcli, BigDecimal pecliDescli, Integer pecliIndtyp, Set<PevntVentas> pevntVentases) {
       this.pecliNomcli = pecliNomcli;
       this.pecliCitcli = pecliCitcli;
       this.pecliDescli = pecliDescli;
       this.pecliIndtyp = pecliIndtyp;
       this.pevntVentases = pevntVentases;
    }
   
    public Integer getPecliNumcli() {
        return this.pecliNumcli;
    }
    
    public void setPecliNumcli(Integer pecliNumcli) {
        this.pecliNumcli = pecliNumcli;
    }
    public String getPecliNomcli() {
        return this.pecliNomcli;
    }
    
    public void setPecliNomcli(String pecliNomcli) {
        this.pecliNomcli = pecliNomcli;
    }
    public String getPecliCitcli() {
        return this.pecliCitcli;
    }
    
    public void setPecliCitcli(String pecliCitcli) {
        this.pecliCitcli = pecliCitcli;
    }
    public BigDecimal getPecliDescli() {
        return this.pecliDescli;
    }
    
    public void setPecliDescli(BigDecimal pecliDescli) {
        this.pecliDescli = pecliDescli;
    }
    public Integer getPecliIndtyp() {
        return this.pecliIndtyp;
    }
    
    public void setPecliIndtyp(Integer pecliIndtyp) {
        this.pecliIndtyp = pecliIndtyp;
    }
    public Set<PevntVentas> getPevntVentases() {
        return this.pevntVentases;
    }
    
    public void setPevntVentases(Set<PevntVentas> pevntVentases) {
        this.pevntVentases = pevntVentases;
    }




}


