package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pedet generated by hbm2java
 */
public class Pedet  implements java.io.Serializable {


     private PedetId id;
     private PeartArticulo peartArticulo;
     private PevntVentas pevntVentas;
     private int pedetCant;
     private BigDecimal pedetTotite;

    public Pedet() {
    }

    public Pedet(PedetId id, PeartArticulo peartArticulo, PevntVentas pevntVentas, int pedetCant, BigDecimal pedetTotite) {
       this.id = id;
       this.peartArticulo = peartArticulo;
       this.pevntVentas = pevntVentas;
       this.pedetCant = pedetCant;
       this.pedetTotite = pedetTotite;
    }
   
    public PedetId getId() {
        return this.id;
    }
    
    public void setId(PedetId id) {
        this.id = id;
    }
    public PeartArticulo getPeartArticulo() {
        return this.peartArticulo;
    }
    
    public void setPeartArticulo(PeartArticulo peartArticulo) {
        this.peartArticulo = peartArticulo;
    }
    public PevntVentas getPevntVentas() {
        return this.pevntVentas;
    }
    
    public void setPevntVentas(PevntVentas pevntVentas) {
        this.pevntVentas = pevntVentas;
    }
    public int getPedetCant() {
        return this.pedetCant;
    }
    
    public void setPedetCant(int pedetCant) {
        this.pedetCant = pedetCant;
    }
    public BigDecimal getPedetTotite() {
        return this.pedetTotite;
    }
    
    public void setPedetTotite(BigDecimal pedetTotite) {
        this.pedetTotite = pedetTotite;
    }




}


