package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PedetDetalle generated by hbm2java
 */
public class PedetDetalle  implements java.io.Serializable {


     private PedetDetalleId id;
     private PeartArticulo peartArticulo;
     private PevntVentas pevntVentas;
     private int pedetCant;
     private BigDecimal pedetTotite;

    public PedetDetalle() {
    }

    public PedetDetalle(PedetDetalleId id, PeartArticulo peartArticulo, PevntVentas pevntVentas, int pedetCant, BigDecimal pedetTotite) {
       this.id = id;
       this.peartArticulo = peartArticulo;
       this.pevntVentas = pevntVentas;
       this.pedetCant = pedetCant;
       this.pedetTotite = pedetTotite;
    }
   
    public PedetDetalleId getId() {
        return this.id;
    }
    
    public void setId(PedetDetalleId id) {
        this.id = id;
    }
    public PeartArticulo getPeartArticulo() {
        return this.peartArticulo;
    }
    
    public void setPeartArticulo(PeartArticulo peartArticulo) {
        this.peartArticulo = peartArticulo;
    }
    public PevntVentas getPevntVentas() {
        return this.pevntVentas;
    }
    
    public void setPevntVentas(PevntVentas pevntVentas) {
        this.pevntVentas = pevntVentas;
    }
    public int getPedetCant() {
        return this.pedetCant;
    }
    
    public void setPedetCant(int pedetCant) {
        this.pedetCant = pedetCant;
    }
    public BigDecimal getPedetTotite() {
        return this.pedetTotite;
    }
    
    public void setPedetTotite(BigDecimal pedetTotite) {
        this.pedetTotite = pedetTotite;
    }




}


