package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1



/**
 * PedetDetalleId generated by hbm2java
 */
public class PedetDetalleId  implements java.io.Serializable {


     private int peartNumart;
     private int pevntNumord;

    public PedetDetalleId() {
    }

    public PedetDetalleId(int peartNumart, int pevntNumord) {
       this.peartNumart = peartNumart;
       this.pevntNumord = pevntNumord;
    }
   
    public int getPeartNumart() {
        return this.peartNumart;
    }
    
    public void setPeartNumart(int peartNumart) {
        this.peartNumart = peartNumart;
    }
    public int getPevntNumord() {
        return this.pevntNumord;
    }
    
    public void setPevntNumord(int pevntNumord) {
        this.pevntNumord = pevntNumord;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedetDetalleId) ) return false;
		 PedetDetalleId castOther = ( PedetDetalleId ) other; 
         
		 return (this.getPeartNumart()==castOther.getPeartNumart())
 && (this.getPevntNumord()==castOther.getPevntNumord());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPeartNumart();
         result = 37 * result + this.getPevntNumord();
         return result;
   }   


}


