package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1



/**
 * PedetId generated by hbm2java
 */
public class PedetId  implements java.io.Serializable {


     private int peartNumart;
     private int pevntNumord;

    public PedetId() {
    }

    public PedetId(int peartNumart, int pevntNumord) {
       this.peartNumart = peartNumart;
       this.pevntNumord = pevntNumord;
    }
   
    public int getPeartNumart() {
        return this.peartNumart;
    }
    
    public void setPeartNumart(int peartNumart) {
        this.peartNumart = peartNumart;
    }
    public int getPevntNumord() {
        return this.pevntNumord;
    }
    
    public void setPevntNumord(int pevntNumord) {
        this.pevntNumord = pevntNumord;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedetId) ) return false;
		 PedetId castOther = ( PedetId ) other; 
         
		 return (this.getPeartNumart()==castOther.getPeartNumart())
 && (this.getPevntNumord()==castOther.getPevntNumord());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPeartNumart();
         result = 37 * result + this.getPevntNumord();
         return result;
   }   


}


