package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeempEmplea generated by hbm2java
 */
public class PeempEmplea  implements java.io.Serializable {


     private Integer peempNumemp;
     private SeusuUsuari seusuUsuari;
     private String peempNomemp;
     private String cedulaEmpleado;
     private Date peempFecnac;
     private BigDecimal peempSalemp;
     private BigDecimal peempComemp;
     private String peempOfiemp;
     private String peempTelemp;
     private String peempCelemp;
     private String peempEmaemp;
     private Integer peempIndtyp;
     private Set<PevntVentas> pevntVentases = new HashSet<PevntVentas>(0);
     private Set<SeusuUsuari> seusuUsuaris = new HashSet<SeusuUsuari>(0);

    public PeempEmplea() {
    }

	
    public PeempEmplea(SeusuUsuari seusuUsuari, String peempNomemp, Date peempFecnac) {
        this.seusuUsuari = seusuUsuari;
        this.peempNomemp = peempNomemp;
        this.peempFecnac = peempFecnac;
    }
    public PeempEmplea(SeusuUsuari seusuUsuari, String peempNomemp, String cedulaEmpleado, Date peempFecnac, BigDecimal peempSalemp, BigDecimal peempComemp, String peempOfiemp, String peempTelemp, String peempCelemp, String peempEmaemp, Integer peempIndtyp, Set<PevntVentas> pevntVentases, Set<SeusuUsuari> seusuUsuaris) {
       this.seusuUsuari = seusuUsuari;
       this.peempNomemp = peempNomemp;
       this.cedulaEmpleado = cedulaEmpleado;
       this.peempFecnac = peempFecnac;
       this.peempSalemp = peempSalemp;
       this.peempComemp = peempComemp;
       this.peempOfiemp = peempOfiemp;
       this.peempTelemp = peempTelemp;
       this.peempCelemp = peempCelemp;
       this.peempEmaemp = peempEmaemp;
       this.peempIndtyp = peempIndtyp;
       this.pevntVentases = pevntVentases;
       this.seusuUsuaris = seusuUsuaris;
    }
   
    public Integer getPeempNumemp() {
        return this.peempNumemp;
    }
    
    public void setPeempNumemp(Integer peempNumemp) {
        this.peempNumemp = peempNumemp;
    }
    public SeusuUsuari getSeusuUsuari() {
        return this.seusuUsuari;
    }
    
    public void setSeusuUsuari(SeusuUsuari seusuUsuari) {
        this.seusuUsuari = seusuUsuari;
    }
    public String getPeempNomemp() {
        return this.peempNomemp;
    }
    
    public void setPeempNomemp(String peempNomemp) {
        this.peempNomemp = peempNomemp;
    }
    public String getCedulaEmpleado() {
        return this.cedulaEmpleado;
    }
    
    public void setCedulaEmpleado(String cedulaEmpleado) {
        this.cedulaEmpleado = cedulaEmpleado;
    }
    public Date getPeempFecnac() {
        return this.peempFecnac;
    }
    
    public void setPeempFecnac(Date peempFecnac) {
        this.peempFecnac = peempFecnac;
    }
    public BigDecimal getPeempSalemp() {
        return this.peempSalemp;
    }
    
    public void setPeempSalemp(BigDecimal peempSalemp) {
        this.peempSalemp = peempSalemp;
    }
    public BigDecimal getPeempComemp() {
        return this.peempComemp;
    }
    
    public void setPeempComemp(BigDecimal peempComemp) {
        this.peempComemp = peempComemp;
    }
    public String getPeempOfiemp() {
        return this.peempOfiemp;
    }
    
    public void setPeempOfiemp(String peempOfiemp) {
        this.peempOfiemp = peempOfiemp;
    }
    public String getPeempTelemp() {
        return this.peempTelemp;
    }
    
    public void setPeempTelemp(String peempTelemp) {
        this.peempTelemp = peempTelemp;
    }
    public String getPeempCelemp() {
        return this.peempCelemp;
    }
    
    public void setPeempCelemp(String peempCelemp) {
        this.peempCelemp = peempCelemp;
    }
    public String getPeempEmaemp() {
        return this.peempEmaemp;
    }
    
    public void setPeempEmaemp(String peempEmaemp) {
        this.peempEmaemp = peempEmaemp;
    }
    public Integer getPeempIndtyp() {
        return this.peempIndtyp;
    }
    
    public void setPeempIndtyp(Integer peempIndtyp) {
        this.peempIndtyp = peempIndtyp;
    }
    public Set<PevntVentas> getPevntVentases() {
        return this.pevntVentases;
    }
    
    public void setPevntVentases(Set<PevntVentas> pevntVentases) {
        this.pevntVentases = pevntVentases;
    }
    public Set<SeusuUsuari> getSeusuUsuaris() {
        return this.seusuUsuaris;
    }
    
    public void setSeusuUsuaris(Set<SeusuUsuari> seusuUsuaris) {
        this.seusuUsuaris = seusuUsuaris;
    }




}


