package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PeempEmplea generated by hbm2java
 */
public class PeempEmplea  implements java.io.Serializable {


     private Integer peempNumemp;
     private SeusuUsuari seusuUsuari;
     private String peempNomemp;
     private int peempEdaemp;
     private BigDecimal peempSalemp;
     private BigDecimal peempComemp;
     private String peempOfiemp;
     private String peempTelemp;
     private String peempCelemp;
     private String peempEmaemp;
     private Integer peempIndtyp;
     private Set<PevntVentas> pevntVentases = new HashSet<PevntVentas>(0);
     private Set<SeusuUsuari> seusuUsuaris = new HashSet<SeusuUsuari>(0);

    public PeempEmplea() {
    }

	
    public PeempEmplea(SeusuUsuari seusuUsuari, String peempNomemp, int peempEdaemp, BigDecimal peempSalemp, BigDecimal peempComemp) {
        this.seusuUsuari = seusuUsuari;
        this.peempNomemp = peempNomemp;
        this.peempEdaemp = peempEdaemp;
        this.peempSalemp = peempSalemp;
        this.peempComemp = peempComemp;
    }
    public PeempEmplea(SeusuUsuari seusuUsuari, String peempNomemp, int peempEdaemp, BigDecimal peempSalemp, BigDecimal peempComemp, String peempOfiemp, String peempTelemp, String peempCelemp, String peempEmaemp, Integer peempIndtyp, Set<PevntVentas> pevntVentases, Set<SeusuUsuari> seusuUsuaris) {
       this.seusuUsuari = seusuUsuari;
       this.peempNomemp = peempNomemp;
       this.peempEdaemp = peempEdaemp;
       this.peempSalemp = peempSalemp;
       this.peempComemp = peempComemp;
       this.peempOfiemp = peempOfiemp;
       this.peempTelemp = peempTelemp;
       this.peempCelemp = peempCelemp;
       this.peempEmaemp = peempEmaemp;
       this.peempIndtyp = peempIndtyp;
       this.pevntVentases = pevntVentases;
       this.seusuUsuaris = seusuUsuaris;
    }
   
    public Integer getPeempNumemp() {
        return this.peempNumemp;
    }
    
    public void setPeempNumemp(Integer peempNumemp) {
        this.peempNumemp = peempNumemp;
    }
    public SeusuUsuari getSeusuUsuari() {
        return this.seusuUsuari;
    }
    
    public void setSeusuUsuari(SeusuUsuari seusuUsuari) {
        this.seusuUsuari = seusuUsuari;
    }
    public String getPeempNomemp() {
        return this.peempNomemp;
    }
    
    public void setPeempNomemp(String peempNomemp) {
        this.peempNomemp = peempNomemp;
    }
    public int getPeempEdaemp() {
        return this.peempEdaemp;
    }
    
    public void setPeempEdaemp(int peempEdaemp) {
        this.peempEdaemp = peempEdaemp;
    }
    public BigDecimal getPeempSalemp() {
        return this.peempSalemp;
    }
    
    public void setPeempSalemp(BigDecimal peempSalemp) {
        this.peempSalemp = peempSalemp;
    }
    public BigDecimal getPeempComemp() {
        return this.peempComemp;
    }
    
    public void setPeempComemp(BigDecimal peempComemp) {
        this.peempComemp = peempComemp;
    }
    public String getPeempOfiemp() {
        return this.peempOfiemp;
    }
    
    public void setPeempOfiemp(String peempOfiemp) {
        this.peempOfiemp = peempOfiemp;
    }
    public String getPeempTelemp() {
        return this.peempTelemp;
    }
    
    public void setPeempTelemp(String peempTelemp) {
        this.peempTelemp = peempTelemp;
    }
    public String getPeempCelemp() {
        return this.peempCelemp;
    }
    
    public void setPeempCelemp(String peempCelemp) {
        this.peempCelemp = peempCelemp;
    }
    public String getPeempEmaemp() {
        return this.peempEmaemp;
    }
    
    public void setPeempEmaemp(String peempEmaemp) {
        this.peempEmaemp = peempEmaemp;
    }
    public Integer getPeempIndtyp() {
        return this.peempIndtyp;
    }
    
    public void setPeempIndtyp(Integer peempIndtyp) {
        this.peempIndtyp = peempIndtyp;
    }
    public Set<PevntVentas> getPevntVentases() {
        return this.pevntVentases;
    }
    
    public void setPevntVentases(Set<PevntVentas> pevntVentases) {
        this.pevntVentases = pevntVentases;
    }
    public Set<SeusuUsuari> getSeusuUsuaris() {
        return this.seusuUsuaris;
    }
    
    public void setSeusuUsuaris(Set<SeusuUsuari> seusuUsuaris) {
        this.seusuUsuaris = seusuUsuaris;
    }




}


