package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PevntVentas generated by hbm2java
 */
public class PevntVentas  implements java.io.Serializable {


     private Integer pevntNumord;
     private PecliCliente pecliCliente;
     private PeempEmplea peempEmplea;
     private BigDecimal pevntTotven;
     private String pevntDirent;
     private Date pevntFecpag;
     private String pevntTippag;
     private String pevntTipven;
     private Set<PedetDetalle> pedetDetalles = new HashSet<PedetDetalle>(0);

    public PevntVentas() {
    }

	
    public PevntVentas(PecliCliente pecliCliente, PeempEmplea peempEmplea, BigDecimal pevntTotven, String pevntDirent, Date pevntFecpag, String pevntTippag, String pevntTipven) {
        this.pecliCliente = pecliCliente;
        this.peempEmplea = peempEmplea;
        this.pevntTotven = pevntTotven;
        this.pevntDirent = pevntDirent;
        this.pevntFecpag = pevntFecpag;
        this.pevntTippag = pevntTippag;
        this.pevntTipven = pevntTipven;
    }
    public PevntVentas(PecliCliente pecliCliente, PeempEmplea peempEmplea, BigDecimal pevntTotven, String pevntDirent, Date pevntFecpag, String pevntTippag, String pevntTipven, Set<PedetDetalle> pedetDetalles) {
       this.pecliCliente = pecliCliente;
       this.peempEmplea = peempEmplea;
       this.pevntTotven = pevntTotven;
       this.pevntDirent = pevntDirent;
       this.pevntFecpag = pevntFecpag;
       this.pevntTippag = pevntTippag;
       this.pevntTipven = pevntTipven;
       this.pedetDetalles = pedetDetalles;
    }
   
    public Integer getPevntNumord() {
        return this.pevntNumord;
    }
    
    public void setPevntNumord(Integer pevntNumord) {
        this.pevntNumord = pevntNumord;
    }
    public PecliCliente getPecliCliente() {
        return this.pecliCliente;
    }
    
    public void setPecliCliente(PecliCliente pecliCliente) {
        this.pecliCliente = pecliCliente;
    }
    public PeempEmplea getPeempEmplea() {
        return this.peempEmplea;
    }
    
    public void setPeempEmplea(PeempEmplea peempEmplea) {
        this.peempEmplea = peempEmplea;
    }
    public BigDecimal getPevntTotven() {
        return this.pevntTotven;
    }
    
    public void setPevntTotven(BigDecimal pevntTotven) {
        this.pevntTotven = pevntTotven;
    }
    public String getPevntDirent() {
        return this.pevntDirent;
    }
    
    public void setPevntDirent(String pevntDirent) {
        this.pevntDirent = pevntDirent;
    }
    public Date getPevntFecpag() {
        return this.pevntFecpag;
    }
    
    public void setPevntFecpag(Date pevntFecpag) {
        this.pevntFecpag = pevntFecpag;
    }
    public String getPevntTippag() {
        return this.pevntTippag;
    }
    
    public void setPevntTippag(String pevntTippag) {
        this.pevntTippag = pevntTippag;
    }
    public String getPevntTipven() {
        return this.pevntTipven;
    }
    
    public void setPevntTipven(String pevntTipven) {
        this.pevntTipven = pevntTipven;
    }
    public Set<PedetDetalle> getPedetDetalles() {
        return this.pedetDetalles;
    }
    
    public void setPedetDetalles(Set<PedetDetalle> pedetDetalles) {
        this.pedetDetalles = pedetDetalles;
    }




}


