package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SeopcOpcion generated by hbm2java
 */
public class SeopcOpcion  implements java.io.Serializable {


     private Integer seopcCodopc;
     private SeopcOpcion seopcOpcion;
     private SesisSistem sesisSistem;
     private SevenVentan sevenVentan;
     private String seopcNomopc;
     private String seopcDesopc;
     private Set<SeopcOpcion> seopcOpcions = new HashSet<SeopcOpcion>(0);
     private Set<SeoppOpcper> seoppOpcpers = new HashSet<SeoppOpcper>(0);
     private Set<SevenVentan> sevenVentans = new HashSet<SevenVentan>(0);

    public SeopcOpcion() {
    }

	
    public SeopcOpcion(String seopcNomopc) {
        this.seopcNomopc = seopcNomopc;
    }
    public SeopcOpcion(SeopcOpcion seopcOpcion, SesisSistem sesisSistem, SevenVentan sevenVentan, String seopcNomopc, String seopcDesopc, Set<SeopcOpcion> seopcOpcions, Set<SeoppOpcper> seoppOpcpers, Set<SevenVentan> sevenVentans) {
       this.seopcOpcion = seopcOpcion;
       this.sesisSistem = sesisSistem;
       this.sevenVentan = sevenVentan;
       this.seopcNomopc = seopcNomopc;
       this.seopcDesopc = seopcDesopc;
       this.seopcOpcions = seopcOpcions;
       this.seoppOpcpers = seoppOpcpers;
       this.sevenVentans = sevenVentans;
    }
   
    public Integer getSeopcCodopc() {
        return this.seopcCodopc;
    }
    
    public void setSeopcCodopc(Integer seopcCodopc) {
        this.seopcCodopc = seopcCodopc;
    }
    public SeopcOpcion getSeopcOpcion() {
        return this.seopcOpcion;
    }
    
    public void setSeopcOpcion(SeopcOpcion seopcOpcion) {
        this.seopcOpcion = seopcOpcion;
    }
    public SesisSistem getSesisSistem() {
        return this.sesisSistem;
    }
    
    public void setSesisSistem(SesisSistem sesisSistem) {
        this.sesisSistem = sesisSistem;
    }
    public SevenVentan getSevenVentan() {
        return this.sevenVentan;
    }
    
    public void setSevenVentan(SevenVentan sevenVentan) {
        this.sevenVentan = sevenVentan;
    }
    public String getSeopcNomopc() {
        return this.seopcNomopc;
    }
    
    public void setSeopcNomopc(String seopcNomopc) {
        this.seopcNomopc = seopcNomopc;
    }
    public String getSeopcDesopc() {
        return this.seopcDesopc;
    }
    
    public void setSeopcDesopc(String seopcDesopc) {
        this.seopcDesopc = seopcDesopc;
    }
    public Set<SeopcOpcion> getSeopcOpcions() {
        return this.seopcOpcions;
    }
    
    public void setSeopcOpcions(Set<SeopcOpcion> seopcOpcions) {
        this.seopcOpcions = seopcOpcions;
    }
    public Set<SeoppOpcper> getSeoppOpcpers() {
        return this.seoppOpcpers;
    }
    
    public void setSeoppOpcpers(Set<SeoppOpcper> seoppOpcpers) {
        this.seoppOpcpers = seoppOpcpers;
    }
    public Set<SevenVentan> getSevenVentans() {
        return this.sevenVentans;
    }
    
    public void setSevenVentans(Set<SevenVentan> sevenVentans) {
        this.sevenVentans = sevenVentans;
    }




}


