package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SeperPerfil generated by hbm2java
 */
public class SeperPerfil  implements java.io.Serializable {


     private Integer seperCodper;
     private String seperNomper;
     private String seperDesper;
     private Set<SeoppOpcper> seoppOpcpers = new HashSet<SeoppOpcper>(0);
     private Set<SeuxpUsxper> seuxpUsxpers = new HashSet<SeuxpUsxper>(0);

    public SeperPerfil() {
    }

	
    public SeperPerfil(String seperNomper) {
        this.seperNomper = seperNomper;
    }
    public SeperPerfil(String seperNomper, String seperDesper, Set<SeoppOpcper> seoppOpcpers, Set<SeuxpUsxper> seuxpUsxpers) {
       this.seperNomper = seperNomper;
       this.seperDesper = seperDesper;
       this.seoppOpcpers = seoppOpcpers;
       this.seuxpUsxpers = seuxpUsxpers;
    }
   
    public Integer getSeperCodper() {
        return this.seperCodper;
    }
    
    public void setSeperCodper(Integer seperCodper) {
        this.seperCodper = seperCodper;
    }
    public String getSeperNomper() {
        return this.seperNomper;
    }
    
    public void setSeperNomper(String seperNomper) {
        this.seperNomper = seperNomper;
    }
    public String getSeperDesper() {
        return this.seperDesper;
    }
    
    public void setSeperDesper(String seperDesper) {
        this.seperDesper = seperDesper;
    }
    public Set<SeoppOpcper> getSeoppOpcpers() {
        return this.seoppOpcpers;
    }
    
    public void setSeoppOpcpers(Set<SeoppOpcper> seoppOpcpers) {
        this.seoppOpcpers = seoppOpcpers;
    }
    public Set<SeuxpUsxper> getSeuxpUsxpers() {
        return this.seuxpUsxpers;
    }
    
    public void setSeuxpUsxpers(Set<SeuxpUsxper> seuxpUsxpers) {
        this.seuxpUsxpers = seuxpUsxpers;
    }




}


