package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1



/**
 * SepriPrivil generated by hbm2java
 */
public class SepriPrivil  implements java.io.Serializable {


     private SepriPrivilId id;
     private SeoppOpcper seoppOpcper;
     private boolean sepriInsert;
     private boolean sepriModifi;
     private boolean sepriElimin;
     private boolean sepriConsul;

    public SepriPrivil() {
    }

    public SepriPrivil(SeoppOpcper seoppOpcper, boolean sepriInsert, boolean sepriModifi, boolean sepriElimin, boolean sepriConsul) {
       this.seoppOpcper = seoppOpcper;
       this.sepriInsert = sepriInsert;
       this.sepriModifi = sepriModifi;
       this.sepriElimin = sepriElimin;
       this.sepriConsul = sepriConsul;
    }
   
    public SepriPrivilId getId() {
        return this.id;
    }
    
    public void setId(SepriPrivilId id) {
        this.id = id;
    }
    public SeoppOpcper getSeoppOpcper() {
        return this.seoppOpcper;
    }
    
    public void setSeoppOpcper(SeoppOpcper seoppOpcper) {
        this.seoppOpcper = seoppOpcper;
    }
    public boolean isSepriInsert() {
        return this.sepriInsert;
    }
    
    public void setSepriInsert(boolean sepriInsert) {
        this.sepriInsert = sepriInsert;
    }
    public boolean isSepriModifi() {
        return this.sepriModifi;
    }
    
    public void setSepriModifi(boolean sepriModifi) {
        this.sepriModifi = sepriModifi;
    }
    public boolean isSepriElimin() {
        return this.sepriElimin;
    }
    
    public void setSepriElimin(boolean sepriElimin) {
        this.sepriElimin = sepriElimin;
    }
    public boolean isSepriConsul() {
        return this.sepriConsul;
    }
    
    public void setSepriConsul(boolean sepriConsul) {
        this.sepriConsul = sepriConsul;
    }




}


