package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SeusuUsuari generated by hbm2java
 */
public class SeusuUsuari  implements java.io.Serializable {


     private String seusuNombre;
     private PeempEmplea peempEmplea;
     private String seusuPasswd;
     private String seusuFirmae;
     private Date seusuUltcmb;
     private Date seusuCreaci;
     private Boolean seusuLogged;
     private Set<PeempEmplea> peempEmpleas = new HashSet<PeempEmplea>(0);
     private Set<SeuxpUsxper> seuxpUsxpers = new HashSet<SeuxpUsxper>(0);

    public SeusuUsuari() {
    }

	
    public SeusuUsuari(String seusuNombre, String seusuPasswd, Date seusuCreaci) {
        this.seusuNombre = seusuNombre;
        this.seusuPasswd = seusuPasswd;
        this.seusuCreaci = seusuCreaci;
    }
    public SeusuUsuari(String seusuNombre, PeempEmplea peempEmplea, String seusuPasswd, String seusuFirmae, Date seusuUltcmb, Date seusuCreaci, Boolean seusuLogged, Set<PeempEmplea> peempEmpleas, Set<SeuxpUsxper> seuxpUsxpers) {
       this.seusuNombre = seusuNombre;
       this.peempEmplea = peempEmplea;
       this.seusuPasswd = seusuPasswd;
       this.seusuFirmae = seusuFirmae;
       this.seusuUltcmb = seusuUltcmb;
       this.seusuCreaci = seusuCreaci;
       this.seusuLogged = seusuLogged;
       this.peempEmpleas = peempEmpleas;
       this.seuxpUsxpers = seuxpUsxpers;
    }
   
    public String getSeusuNombre() {
        return this.seusuNombre;
    }
    
    public void setSeusuNombre(String seusuNombre) {
        this.seusuNombre = seusuNombre;
    }
    public PeempEmplea getPeempEmplea() {
        return this.peempEmplea;
    }
    
    public void setPeempEmplea(PeempEmplea peempEmplea) {
        this.peempEmplea = peempEmplea;
    }
    public String getSeusuPasswd() {
        return this.seusuPasswd;
    }
    
    public void setSeusuPasswd(String seusuPasswd) {
        this.seusuPasswd = seusuPasswd;
    }
    public String getSeusuFirmae() {
        return this.seusuFirmae;
    }
    
    public void setSeusuFirmae(String seusuFirmae) {
        this.seusuFirmae = seusuFirmae;
    }
    public Date getSeusuUltcmb() {
        return this.seusuUltcmb;
    }
    
    public void setSeusuUltcmb(Date seusuUltcmb) {
        this.seusuUltcmb = seusuUltcmb;
    }
    public Date getSeusuCreaci() {
        return this.seusuCreaci;
    }
    
    public void setSeusuCreaci(Date seusuCreaci) {
        this.seusuCreaci = seusuCreaci;
    }
    public Boolean getSeusuLogged() {
        return this.seusuLogged;
    }
    
    public void setSeusuLogged(Boolean seusuLogged) {
        this.seusuLogged = seusuLogged;
    }
    public Set<PeempEmplea> getPeempEmpleas() {
        return this.peempEmpleas;
    }
    
    public void setPeempEmpleas(Set<PeempEmplea> peempEmpleas) {
        this.peempEmpleas = peempEmpleas;
    }
    public Set<SeuxpUsxper> getSeuxpUsxpers() {
        return this.seuxpUsxpers;
    }
    
    public void setSeuxpUsxpers(Set<SeuxpUsxper> seuxpUsxpers) {
        this.seuxpUsxpers = seuxpUsxpers;
    }




}


