package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SeuxpUsxper generated by hbm2java
 */
public class SeuxpUsxper  implements java.io.Serializable {


     private SeuxpUsxperId id;
     private SeperPerfil seperPerfil;
     private SeusuUsuari seusuUsuari;
     private Date seuxpFecasi;
     private String seuxpMotivo;
     private Date seuxpFecfin;

    public SeuxpUsxper() {
    }

	
    public SeuxpUsxper(SeuxpUsxperId id, SeperPerfil seperPerfil, SeusuUsuari seusuUsuari, Date seuxpFecasi, String seuxpMotivo) {
        this.id = id;
        this.seperPerfil = seperPerfil;
        this.seusuUsuari = seusuUsuari;
        this.seuxpFecasi = seuxpFecasi;
        this.seuxpMotivo = seuxpMotivo;
    }
    public SeuxpUsxper(SeuxpUsxperId id, SeperPerfil seperPerfil, SeusuUsuari seusuUsuari, Date seuxpFecasi, String seuxpMotivo, Date seuxpFecfin) {
       this.id = id;
       this.seperPerfil = seperPerfil;
       this.seusuUsuari = seusuUsuari;
       this.seuxpFecasi = seuxpFecasi;
       this.seuxpMotivo = seuxpMotivo;
       this.seuxpFecfin = seuxpFecfin;
    }
   
    public SeuxpUsxperId getId() {
        return this.id;
    }
    
    public void setId(SeuxpUsxperId id) {
        this.id = id;
    }
    public SeperPerfil getSeperPerfil() {
        return this.seperPerfil;
    }
    
    public void setSeperPerfil(SeperPerfil seperPerfil) {
        this.seperPerfil = seperPerfil;
    }
    public SeusuUsuari getSeusuUsuari() {
        return this.seusuUsuari;
    }
    
    public void setSeusuUsuari(SeusuUsuari seusuUsuari) {
        this.seusuUsuari = seusuUsuari;
    }
    public Date getSeuxpFecasi() {
        return this.seuxpFecasi;
    }
    
    public void setSeuxpFecasi(Date seuxpFecasi) {
        this.seuxpFecasi = seuxpFecasi;
    }
    public String getSeuxpMotivo() {
        return this.seuxpMotivo;
    }
    
    public void setSeuxpMotivo(String seuxpMotivo) {
        this.seuxpMotivo = seuxpMotivo;
    }
    public Date getSeuxpFecfin() {
        return this.seuxpFecfin;
    }
    
    public void setSeuxpFecfin(Date seuxpFecfin) {
        this.seuxpFecfin = seuxpFecfin;
    }




}


