package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SeuxpUsxper generated by hbm2java
 */
public class SeuxpUsxper  implements java.io.Serializable {


     private SeuxpUsxperId id;
     private SeperPerfil seperPerfil;
     private SeusuUsuari seusuUsuari;
     private Date fechaDeAsignacion;
     private String motivoUsuPer;

    public SeuxpUsxper() {
    }

    public SeuxpUsxper(SeuxpUsxperId id, SeperPerfil seperPerfil, SeusuUsuari seusuUsuari, Date fechaDeAsignacion, String motivoUsuPer) {
       this.id = id;
       this.seperPerfil = seperPerfil;
       this.seusuUsuari = seusuUsuari;
       this.fechaDeAsignacion = fechaDeAsignacion;
       this.motivoUsuPer = motivoUsuPer;
    }
   
    public SeuxpUsxperId getId() {
        return this.id;
    }
    
    public void setId(SeuxpUsxperId id) {
        this.id = id;
    }
    public SeperPerfil getSeperPerfil() {
        return this.seperPerfil;
    }
    
    public void setSeperPerfil(SeperPerfil seperPerfil) {
        this.seperPerfil = seperPerfil;
    }
    public SeusuUsuari getSeusuUsuari() {
        return this.seusuUsuari;
    }
    
    public void setSeusuUsuari(SeusuUsuari seusuUsuari) {
        this.seusuUsuari = seusuUsuari;
    }
    public Date getFechaDeAsignacion() {
        return this.fechaDeAsignacion;
    }
    
    public void setFechaDeAsignacion(Date fechaDeAsignacion) {
        this.fechaDeAsignacion = fechaDeAsignacion;
    }
    public String getMotivoUsuPer() {
        return this.motivoUsuPer;
    }
    
    public void setMotivoUsuPer(String motivoUsuPer) {
        this.motivoUsuPer = motivoUsuPer;
    }




}


