package Model;
// Generated 19/02/2016 10:05:19 by Hibernate Tools 4.3.1



/**
 * SeuxpUsxperId generated by hbm2java
 */
public class SeuxpUsxperId  implements java.io.Serializable {


     private String seusuNombre;
     private int seperCodper;
     private int seuxpCodigo;

    public SeuxpUsxperId() {
    }

    public SeuxpUsxperId(String seusuNombre, int seperCodper, int seuxpCodigo) {
       this.seusuNombre = seusuNombre;
       this.seperCodper = seperCodper;
       this.seuxpCodigo = seuxpCodigo;
    }
   
    public String getSeusuNombre() {
        return this.seusuNombre;
    }
    
    public void setSeusuNombre(String seusuNombre) {
        this.seusuNombre = seusuNombre;
    }
    public int getSeperCodper() {
        return this.seperCodper;
    }
    
    public void setSeperCodper(int seperCodper) {
        this.seperCodper = seperCodper;
    }
    public int getSeuxpCodigo() {
        return this.seuxpCodigo;
    }
    
    public void setSeuxpCodigo(int seuxpCodigo) {
        this.seuxpCodigo = seuxpCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeuxpUsxperId) ) return false;
		 SeuxpUsxperId castOther = ( SeuxpUsxperId ) other; 
         
		 return ( (this.getSeusuNombre()==castOther.getSeusuNombre()) || ( this.getSeusuNombre()!=null && castOther.getSeusuNombre()!=null && this.getSeusuNombre().equals(castOther.getSeusuNombre()) ) )
 && (this.getSeperCodper()==castOther.getSeperCodper())
 && (this.getSeuxpCodigo()==castOther.getSeuxpCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSeusuNombre() == null ? 0 : this.getSeusuNombre().hashCode() );
         result = 37 * result + this.getSeperCodper();
         result = 37 * result + this.getSeuxpCodigo();
         return result;
   }   


}


