package Model;
// Generated 11/02/2016 9:53:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SevenVentan generated by hbm2java
 */
public class SevenVentan  implements java.io.Serializable {


     private Integer codigoVentana;
     private SeopcOpcion seopcOpcion;
     private String nombreVentana;
     private String descripcionVentana;
     private Set<SeopcOpcion> seopcOpcions = new HashSet<SeopcOpcion>(0);

    public SevenVentan() {
    }

    public SevenVentan(SeopcOpcion seopcOpcion, String nombreVentana, String descripcionVentana, Set<SeopcOpcion> seopcOpcions) {
       this.seopcOpcion = seopcOpcion;
       this.nombreVentana = nombreVentana;
       this.descripcionVentana = descripcionVentana;
       this.seopcOpcions = seopcOpcions;
    }
   
    public Integer getCodigoVentana() {
        return this.codigoVentana;
    }
    
    public void setCodigoVentana(Integer codigoVentana) {
        this.codigoVentana = codigoVentana;
    }
    public SeopcOpcion getSeopcOpcion() {
        return this.seopcOpcion;
    }
    
    public void setSeopcOpcion(SeopcOpcion seopcOpcion) {
        this.seopcOpcion = seopcOpcion;
    }
    public String getNombreVentana() {
        return this.nombreVentana;
    }
    
    public void setNombreVentana(String nombreVentana) {
        this.nombreVentana = nombreVentana;
    }
    public String getDescripcionVentana() {
        return this.descripcionVentana;
    }
    
    public void setDescripcionVentana(String descripcionVentana) {
        this.descripcionVentana = descripcionVentana;
    }
    public Set<SeopcOpcion> getSeopcOpcions() {
        return this.seopcOpcions;
    }
    
    public void setSeopcOpcions(Set<SeopcOpcion> seopcOpcions) {
        this.seopcOpcions = seopcOpcions;
    }




}


